-- Phase 2A intentionally has no static identity or operational seed rows.
-- Auth users, memberships, and request fixtures are created transactionally
-- inside database tests.
-- For manual local use, invite a disposable local user and call
-- public.create_organization(name, slug) while authenticated.
